books: list[dict[str | float | bool]] = [
    {'id': 1, 'title': 'Dune', 'author': 'Frank Herbert', 'price': 15.99, 'available': True},
    {'id': 2, 'title': 'Dune Messiah', 'author': 'Frank Herbert', 'price': 15.99, 'available': False},
    {'id': 3, 'title': 'The Three-Body Problem', 'author': 'Liu Cixin', 'price': 21.0, 'available': True},
    {'id': 4, 'title': 'The Name of the Wind', 'author': 'Patrick Rothfuss', 'price': 12.99, 'available': True},
    {'id': 5, 'title': '1984', 'author': 'George Orwell', 'price': 9.99, 'available': False},
    {'id': 6, 'title': 'Brave New World', 'author': 'Aldous Huxley', 'price': 10.99, 'available': True},
    {'id': 7, 'title': 'Fahrenheit 451', 'author': 'Ray Bradbury', 'price': 11.50, 'available': False},
    {'id': 8, 'title': 'Foundation', 'author': 'Isaac Asimov', 'price': 14.99, 'available': True},
    {'id': 9, 'title': 'Hyperion', 'author': 'Dan Simmons', 'price': 16.50, 'available': False},
    {'id': 10, 'title': 'Neuromancer', 'author': 'William Gibson', 'price': 12.99, 'available': True},
    {'id': 11, 'title': 'Snow Crash', 'author': 'Neal Stephenson', 'price': 13.50, 'available': False},
    {'id': 12, 'title': 'The Left Hand of Darkness', 'author': 'Ursula K. Le Guin', 'price': 14.99, 'available': True},
    {'id': 13, 'title': 'The Catcher in the Rye', 'author': 'J.D. Salinger', 'price': 8.99, 'available': False},
    {'id': 14, 'title': 'The Road', 'author': 'Cormac McCarthy', 'price': 11.99, 'available': True},
    {'id': 15, 'title': 'Slaughterhouse-Five', 'author': 'Kurt Vonnegut', 'price': 9.99, 'available': True},
    {'id': 16, 'title': 'American Gods', 'author': 'Neil Gaiman', 'price': 16.99, 'available': False},
    {'id': 17, 'title': 'The Handmaid’s Tale', 'author': 'Margaret Atwood', 'price': 12.50, 'available': True},
    {'id': 18, 'title': 'Neverwhere', 'author': 'Neil Gaiman', 'price': 13.50, 'available': False},
    {'id': 19, 'title': 'Good Omens', 'author': 'Neil Gaiman & Terry Pratchett', 'price': 12.99, 'available': True},
    {'id': 20, 'title': 'The Hobbit', 'author': 'J.R.R. Tolkien', 'price': 10.99, 'available': False},
    {'id': 21, 'title': 'The Lord of the Rings', 'author': 'J.R.R. Tolkien', 'price': 22.99, 'available': True},
    {'id': 22, 'title': 'The Silmarillion', 'author': 'J.R.R. Tolkien', 'price': 18.50, 'available': False},
    {'id': 23, 'title': 'The Hunger Games', 'author': 'Suzanne Collins', 'price': 8.99, 'available': True},
    {'id': 24, 'title': 'Catching Fire', 'author': 'Suzanne Collins', 'price': 8.99, 'available': True},
    {'id': 25, 'title': 'Mockingjay', 'author': 'Suzanne Collins', 'price': 8.99, 'available': False},
    {'id': 26, 'title': 'A Game of Thrones', 'author': 'George R.R. Martin', 'price': 15.50, 'available': True},
    {'id': 27, 'title': 'A Clash of Kings', 'author': 'George R.R. Martin', 'price': 14.99, 'available': False},
    {'id': 28, 'title': 'A Storm of Swords', 'author': 'George R.R. Martin', 'price': 16.99, 'available': True},
    {'id': 29, 'title': 'A Feast for Crows', 'author': 'George R.R. Martin', 'price': 14.50, 'available': False},
    {'id': 30, 'title': 'A Dance with Dragons', 'author': 'George R.R. Martin', 'price': 17.50, 'available': True},
    {'id': 31, 'title': 'The Way of Kings', 'author': 'Brandon Sanderson', 'price': 19.99, 'available': True},
    {'id': 32, 'title': 'Words of Radiance', 'author': 'Brandon Sanderson', 'price': 18.99, 'available': False},
    {'id': 33, 'title': 'Oathbringer', 'author': 'Brandon Sanderson', 'price': 19.99, 'available': True},
    {'id': 34, 'title': 'Rhythm of War', 'author': 'Brandon Sanderson', 'price': 20.99, 'available': False},
    {'id': 35, 'title': 'Mistborn: The Final Empire', 'author': 'Brandon Sanderson', 'price': 12.99, 'available': True},
    {'id': 36, 'title': 'The Well of Ascension', 'author': 'Brandon Sanderson', 'price': 12.99, 'available': True},
    {'id': 37, 'title': 'The Hero of Ages', 'author': 'Brandon Sanderson', 'price': 12.99, 'available': False},
    {'id': 38, 'title': 'The Alloy of Law', 'author': 'Brandon Sanderson', 'price': 13.99, 'available': True},
    {'id': 39, 'title': 'Shadows of Self', 'author': 'Brandon Sanderson', 'price': 13.99, 'available': False},
    {'id': 40, 'title': 'The Bands of Mourning', 'author': 'Brandon Sanderson', 'price': 13.99, 'available': True},
    {'id': 41, 'title': 'Elantris', 'author': 'Brandon Sanderson', 'price': 12.99, 'available': True},
    {'id': 42, 'title': 'Warbreaker', 'author': 'Brandon Sanderson', 'price': 13.99, 'available': False},
    {'id': 43, 'title': 'The Lies of Locke Lamora', 'author': 'Scott Lynch', 'price': 12.99, 'available': True},
    {'id': 44, 'title': 'Red Seas Under Red Skies', 'author': 'Scott Lynch', 'price': 13.99, 'available': False},
    {'id': 45, 'title': 'Republic of Thieves', 'author': 'Scott Lynch', 'price': 13.99, 'available': True},
    {'id': 46, 'title': 'The Blade Itself', 'author': 'Joe Abercrombie', 'price': 13.50, 'available': False},
    {'id': 47, 'title': 'Before They Are Hanged', 'author': 'Joe Abercrombie', 'price': 13.99, 'available': True},
    {'id': 48, 'title': 'Last Argument of Kings', 'author': 'Joe Abercrombie', 'price': 14.99, 'available': False},
    {'id': 49, 'title': 'Best Served Cold', 'author': 'Joe Abercrombie', 'price': 14.99, 'available': True},
    {'id': 50, 'title': 'The Heroes', 'author': 'Joe Abercrombie', 'price': 15.99, 'available': False},
    {'id': 51, 'title': 'Red Country', 'author': 'Joe Abercrombie', 'price': 15.50, 'available': True},
    {'id': 52, 'title': 'The Shining', 'author': 'Stephen King', 'price': 10.99, 'available': False},
    {'id': 53, 'title': 'It', 'author': 'Stephen King', 'price': 14.99, 'available': True},
    {'id': 54, 'title': 'Misery', 'author': 'Stephen King', 'price': 12.99, 'available': False},
    {'id': 55, 'title': 'Carrie', 'author': 'Stephen King', 'price': 9.99, 'available': True},
    {'id': 56, 'title': 'The Dark Tower: The Gunslinger', 'author': 'Stephen King', 'price': 11.99, 'available': False},
    {'id': 57, 'title': 'The Dark Tower: The Drawing of the Three', 'author': 'Stephen King', 'price': 12.99, 'available': True},
    {'id': 58, 'title': 'The Dark Tower: The Waste Lands', 'author': 'Stephen King', 'price': 13.50, 'available': False},
    {'id': 59, 'title': 'The Dark Tower: Wizard and Glass', 'author': 'Stephen King', 'price': 14.50, 'available': True},
    {'id': 60, 'title': 'Dracula', 'author': 'Bram Stoker', 'price': 9.99, 'available': True},
    {'id': 61, 'title': 'The Picture of Dorian Gray', 'author': 'Oscar Wilde', 'price': 7.99, 'available': False},
    {'id': 62, 'title': 'Pride and Prejudice', 'author': 'Jane Austen', 'price': 6.99, 'available': True},
    {'id': 63, 'title': 'Emma', 'author': 'Jane Austen', 'price': 6.99, 'available': False},
    {'id': 64, 'title': 'Sense and Sensibility', 'author': 'Jane Austen', 'price': 6.99, 'available': True},
    {'id': 65, 'title': 'Wuthering Heights', 'author': 'Emily Brontë', 'price': 8.99, 'available': False},
    {'id': 66, 'title': 'Jane Eyre', 'author': 'Charlotte Brontë', 'price': 8.99, 'available': True},
    {'id': 67, 'title': 'The Great Gatsby', 'author': 'F. Scott Fitzgerald', 'price': 7.99, 'available': False},
    {'id': 68, 'title': 'To Kill a Mockingbird', 'author': 'Harper Lee', 'price': 8.99, 'available': True},
    {'id': 69, 'title': 'Moby-Dick', 'author': 'Herman Melville', 'price': 10.99, 'available': False},
    {'id': 70, 'title': 'The Odyssey', 'author': 'Homer', 'price': 11.99, 'available': True},
    {'id': 71, 'title': 'The Iliad', 'author': 'Homer', 'price': 11.99, 'available': False},
    {'id': 72, 'title': 'The Brothers Karamazov', 'author': 'Fyodor Dostoevsky', 'price': 14.99, 'available': True},
    {'id': 73, 'title': 'Crime and Punishment', 'author': 'Fyodor Dostoevsky', 'price': 13.99, 'available': False},
    {'id': 74, 'title': 'War and Peace', 'author': 'Leo Tolstoy', 'price': 19.99, 'available': True},
    {'id': 75, 'title': 'Anna Karenina', 'author': 'Leo Tolstoy', 'price': 14.99, 'available': False},
    {'id': 76, 'title': 'Don Quixote', 'author': 'Miguel de Cervantes', 'price': 13.99, 'available': True},
    {'id': 77, 'title': 'Les Misérables', 'author': 'Victor Hugo', 'price': 17.99, 'available': False},
    {'id': 78, 'title': 'The Count of Monte Cristo', 'author': 'Alexandre Dumas', 'price': 16.99, 'available': True},
    {'id': 79, 'title': 'The Stranger', 'author': 'Albert Camus', 'price': 8.99, 'available': False},
    {'id': 80, 'title': 'The Plague', 'author': 'Albert Camus', 'price': 9.99, 'available': True},
    {'id': 81, 'title': 'The Metamorphosis', 'author': 'Franz Kafka', 'price': 7.99, 'available': False},
    {'id': 82, 'title': 'One Hundred Years of Solitude', 'author': 'Gabriel García Márquez', 'price': 12.99, 'available': True},
    {'id': 83, 'title': 'Love in the Time of Cholera', 'author': 'Gabriel García Márquez', 'price': 13.50, 'available': True}
]
